# Generated by Django 4.2.16 on 2024-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
