# Generated by Django 4.2.16 on 2024-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
